### ISSUE TITLE
Detail page to view attributes of credentials stored in the wallet

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-android#13] opened 2020-12-07 07:40 UTC
A details page should be provided allowing the user to view the attributes of credentials stored in the wallet.

**Comment by josmilan** [comment] 2020-12-09 03:07
probably duplicate of #4, can you please check

**Comment by darkchylde** [comment] 2020-12-09 03:10
Not duplicated but related issue. Capability to print credential info.

**Closed** 2020-12-18 11:46 UTC
Labels: enhancement
